services:
  - type: web
    name: pet-health-tracer-backend
    runtime: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: MONGO_URI
        scope: all
        value: mongodb+srv://balagasanjana11:balagasanjana%4011@cluster1.cqvygcp.mongodb.net/pet?appName=Cluster1
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: ${FRONTEND_URL}, https://balagasanjana.github.io/pet-health-tracer

  - type: web
    name: pet-health-tracer-frontend
    runtime: static
    plan: free
    staticPublishPath: ./client/build
    buildCommand: "cd client && npm install && npm run build"
    routes:
      - path: /
        handlers:
          - status: 404
            path: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://pet-health-tracer.onrender.com
